name: Pytest & flake8 control Push
on: push

# Définissez un id de tâche, nommez-le et définissons sur quelle instance nous voulons l'exécuter
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04

# 5 étapes :Un contrôle du dépôt, Configuration de Python sur la VM, L'installation des paquets, L'exécution de nos tests, Le contrôle de la convention Pep8
steps:
  - name: Checkout on master
    uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@master
    with:
      python-version: "3.x"

# Dans les étapes suivantes, nous allons installer deux paquets et exécuter pytest et flake8
- name: Install pytest and flake8
  run: |
    pip install pytest
    pip install flake8

- name: Run tests
  run: |
    pytest

- name: Run flake8
  uses: py-actions/flake8@v2

